function sFiles = average_trials(sFiles)
% function sFiles = average_trials(sFiles)
%
% averages imported trials (sFiles)

% Process: Average: By condition (subject average)
sFiles = bst_process(...
    'CallProcess', 'process_average', ...
    sFiles, [], ...
    'avgtype', 3, ...
    'avg_func', 1, ...  % <HTML>Arithmetic average: <FONT color="#777777">mean(x)</FONT>
    'keepevents', 0);