function sFiles = compute_noise_covariance(sFiles)
% function sFiles = compute_noise_covariance(sFiles)
%
% computes noise covariance from imported trials (sFiles)


% Process: Compute noise covariance
sFiles = bst_process(...
    'CallProcess', 'process_noisecov', ...
    sFiles, [], ...
    'baseline', [-0.1, -0.001], ...
    'dcoffset', 1, ...
    'method', 1, ...  % Full noise covariance matrix
    'copycond', 0, ...
    'copysubj', 0);


